### ISSUE TITLE
Introduce new Config for the State

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-evm-bridge-validator#268]
Separate configurations for node and bridge:
```yaml
# node-config.yml
node:
  database:
    host: 127.0.0.1
    name: hedera_validator
    password:
    port: 5432
    username: validator
  clients:
    evm:
      80001:
        block_confirmations: 5
        node_url: ""
        private_key:
      5:
        block_confirmations: 5
        node_url: ""
        private_key:
    hedera:
      operator:
        account_id:
        private_key:
      network:
    mirror_node:
      api_address: ""
      client_address:
      max_retries: 10
      polling_interval: 5
  log_level: debug
  port: 5200
  recovery:
    start_timestamp:
  validator: true/false
```

```yaml
# bridge-config.yml
bridge-config:
  topic_id:
  networks:
    0: # Hedera
      bridge_account:
      payer_account:
      members:
        -
      tokens:
        "HBAR":
          fee_percentage: 10 # 10.000%
          80001: ""
        "0.0.0":
          fee_percentage: 50
          80001: ""
    80001:
      router_contract_address: ""
      tokens:
        "":
          0: ""
          5: ""
    5:
      router_contract_address: ""
      tokens:
```
